"""model Client

Revision ID: 62e08652d2fc
Revises: f56d36499eeb
Create Date: 2023-11-02 10:48:03.192728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e08652d2fc'
down_revision = 'f56d36499eeb'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('det_sale', 'sale_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('det_sale', 'prod_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('product', 'cat_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('sale', 'cli_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale', 'cli_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('product', 'cat_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('det_sale', 'prod_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('det_sale', 'sale_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
