"""use new models User and Category and Product and Client and Sale and DetSale

Revision ID: e94a0b79dc68
Revises: 
Create Date: 2023-10-29 17:33:32.750211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e94a0b79dc68'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('desc', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category')),
    sa.UniqueConstraint('name', name=op.f('uq_category_name'))
    )
    op.create_table('client',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('names', sa.VARCHAR(length=150), nullable=False),
    sa.Column('surnames', sa.VARCHAR(length=150), nullable=False),
    sa.Column('dni', sa.VARCHAR(length=10), nullable=False),
    sa.Column('address', sa.VARCHAR(length=150), nullable=True),
    sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='genderenum'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client')),
    sa.UniqueConstraint('dni', name=op.f('uq_client_dni'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('name', name=op.f('uq_users_name'))
    )
    op.create_table('product',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('image', sa.VARCHAR(), nullable=True),
    sa.Column('stock', sa.INTEGER(), nullable=True),
    sa.Column('pvp', sa.NUMERIC(precision=9, scale=2), nullable=True),
    sa.Column('cat_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['category.id'], name=op.f('fk_product_cat_id_category'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product')),
    sa.UniqueConstraint('name', name=op.f('uq_product_name'))
    )
    op.create_table('sale',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date_joined', sa.DATE(), nullable=True),
    sa.Column('subtotal', sa.NUMERIC(precision=9, scale=2), nullable=True),
    sa.Column('iva', sa.NUMERIC(precision=9, scale=2), nullable=True),
    sa.Column('total', sa.NUMERIC(precision=9, scale=2), nullable=True),
    sa.Column('cli_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['cli_id'], ['client.id'], name=op.f('fk_sale_cli_id_client'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sale'))
    )
    op.create_table('det_sale',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=9, scale=2), nullable=True),
    sa.Column('cant', sa.INTEGER(), nullable=True),
    sa.Column('subtotal', sa.NUMERIC(precision=9, scale=2), nullable=True),
    sa.Column('sale_id', sa.UUID(), nullable=True),
    sa.Column('prod_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['prod_id'], ['product.id'], name=op.f('fk_det_sale_prod_id_product'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], name=op.f('fk_det_sale_sale_id_sale'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_det_sale'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('det_sale')
    op.drop_table('sale')
    op.drop_table('product')
    op.drop_table('users')
    op.drop_table('client')
    op.drop_table('category')
    # ### end Alembic commands ###
