"""model Sale

Revision ID: bafc48930150
Revises: 62e08652d2fc
Create Date: 2023-11-02 14:25:23.981910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bafc48930150'
down_revision = '62e08652d2fc'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
