"""model Client

Revision ID: f56d36499eeb
Revises: e94a0b79dc68
Create Date: 2023-11-01 15:58:18.776188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56d36499eeb'
down_revision = 'e94a0b79dc68'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('balance', sa.NUMERIC(precision=9, scale=2), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'balance')
    # ### end Alembic commands ###
