"""model Sale

Revision ID: 1e3814be8abd
Revises: bafc48930150
Create Date: 2023-11-02 14:37:00.621275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e3814be8abd'
down_revision = 'bafc48930150'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
